<a href="https://colab.research.google.com/github/maggie8801/Standardzation_test/blob/main/Standardzation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Z-score

#### import package

In [5]:
import numpy as np
from scipy import stats

In [6]:
data = np.array([200,300,400,600,1000])
data

array([ 200,  300,  400,  600, 1000])

In [7]:
type(data) #得知型態為陣列

numpy.ndarray

In [18]:
data.shape #看維度 #前面是roll後面是column #得知data為一維資料

(5,)

In [25]:
zscore = stats.zscore(data)
zscore

array([-1.06066017, -0.70710678, -0.35355339,  0.35355339,  1.76776695])

### Min-Max

#### import package

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() #這個套件只支援二維資料
data2 = np.array([[200],[300],[400],[600],[1000]]) #將資料打成二維形式
data2

array([[ 200],
       [ 300],
       [ 400],
       [ 600],
       [1000]])

In [19]:
data2.shape #得知data2為二維資料

(5, 1)

In [22]:
minmax = scaler.fit_transform(data2) #做演算法先fit進去訓練再transform
minmax

array([[0.   ],
       [0.125],
       [0.25 ],
       [0.5  ],
       [1.   ]])

In [24]:
print(data2)
print(data2.shape)

[[ 200]
 [ 300]
 [ 400]
 [ 600]
 [1000]]
(5, 1)
